version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
    - "27017:27017"
    restart: always

volumes:
  mongo_data:

